version: '3'

services:
  local_proxy:
    build: ../5erflies-hotel-photo-carousel-proxy/
    volumes:
      - .:/src/app
      - /src/app/node_modules/
    # depends_on:
    #   - 'database'
    ports:
      - '3000:3000'

  # database:
  #   image: mongo:latest